services:
  - type: web
    name: realtime-editor
    env: node
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=4096 