services:
  - type: web
    name: realtime-editor
    env: node
    nodeVersion: 18
    buildCommand: npm install --legacy-peer-deps
    startCommand: npm run build && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=4096 